import Head from 'next/head';

import Banner from '@/components/banner/Banner';
import Navbar from '@/components/navbar/Navbar';

export default function Home() {
	return (
		<>
			<Head>
				<title>Netflix Clone</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
			</Head>
			<main>
				<Navbar username="Davis Ochieng" />
				<Banner
					title="Margin"
					subTitle="Business"
					imgUrl="/static/clifford.webp"
				/>
			</main>
		</>
	);
}
