import Head from 'next/head';

import Banner from '@/components/banner/Banner';
import Navbar from '@/components/navbar/Navbar';
import Card from '@/components/card/Card';
import SectionCards from '@/components/section-cards/SectionCards';

import { getVideos } from '@/lib/vodeos';

import styles from '@/styles/Home.module.css';

export default function Home({ videos }) {
	return (
		<>
			<Head>
				<title>Netflix Clone</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
			</Head>
			<main>
				<Navbar username="Davis Ochieng" />
				<Banner
					title="Margin"
					subTitle="Business"
					imgUrl="/static/clifford.webp"
				/>
				<div className={styles.sectionWrapper}>
					<SectionCards title="Disney" videos={videos} />
				</div>
			</main>
		</>
	);
}

export async function getServerSideProps(context) {
	const videos = await getVideos();
	return {
		props: {
			videos,
		},
	};
}
